name: goldeconplus
main: org.goldecon.goldeconplus.Goldecon
version: 1.7_alpha2
authors: [Stoolbend, boardinggamer, Kierrow]
description: A simple economy based around gold nuggets.
permissions:
 goldecon.core.use:
  description: use goldecon
  default: true
 goldecon.shop.use:
  description: use shops
  default: true
 goldecon.shop.create:
  description: create shops
  default: op
 goldecon.shop.admin:
  description: destroy and update any shop
  default: op
 goldecon.bank.use:
  description: use goldecon banks
  default: false
 goldecon.bank.admin:
  description: use goldecon bank admin functions
  default: false
 goldecon.region.use:
  description: use region shops
  default: true
 goldecon.region.sell:
  description: sell WG regions you can build on
  default: op
 goldecon.region.admin:
  description: sell any WG region
  default: op
commands:
 ge:
  description:
  usage: <command>
  aliases: [goldecon]
 geshop:
  description:
  usage: <command>
  aliases: [goldeconshop, ges]
 geshophelp:
  description: help menu for shops
  usage: <command>
  aliases: [goldeconshophelp, geshelp]
 gebank:
  description:
  usage: <command>
  aliases: [goldeconbank]
 geregion:
  description:
  usage: <command>
  aliases: [goldeconregion, ger]